// 打包/React_Pack_Vite/src/views/Picture/index.tsx
import React, { useState, useEffect } from 'react';
const Picture: React.FC = () => {
    const [List, setList] = useState([]);
    const GetPicture = async () => {
        const response = await fetch('/Picture.json');
        const { data } = await response.json();
        setList(data);
    };
    useEffect(() => {
        GetPicture();
    }, []);

    return (
        List.map(item => (<img key={item} src={item} />))
    );
};

export default Picture;

// 打包/Vue3_Pack/src/views/Picture.vue
<template>
  <div>
    <img v-for='(item) in List' :key='item' :src='item' />
  </div>
</template>
<script lang='ts' setup>
import { ref, onMounted } from 'vue';
const List = ref([]);
const GetPicture = async () => {
  const response = await fetch('/Picture.json');
  const { data } = await response.json();
  List.value = data;
};
onMounted(() => {
  GetPicture();
});
</script>
